    <div>
			<a href="https://forum.effectivealtruism.org/users/nunosempere">ea forum</a> |
			<a href="https://forecasting.substack.com/">forecasting newsletter</a> |
			<a href="https://github.com/">github</a> |
			<a href="https://metaforecast.org/">metaforecast</a> |
			<a href="https://quantifieduncertainty.org/">quantified uncertainty</a> |
			<a href="https://twitter.com/NunoSempere">twitter</a>
    </div>

    <div>
      <a href="/about">about</a> |
      <a href="/sitemap">site map</a>
    </div>

